### ISSUE TITLE
Unable to use with Angular CLI App

### ISSUE THREAD

**Issue by yoooee** [Elecweb/emptytext#1]
Thank you for the great write up and supporting files for creating an Angular module from scratch.  I cloned your project and built it without issue.  However, when I create a new application using the Angular CLI, import the EmptyTextModule, and run ng serve, I receive the following error: 

ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file)

**Comment by Elecweb** [comment]
@yoooee I try with angular cli version 1.0.1 but I don't found any issue with it. The error is occured when you use the anonymous (lambda) functionin provider. 

https://github.com/angular/angular-cli/issues/3707
You can fix it by replace  the anonymous (lambda) function with function declarations.

I'm not sure if you modified code in the project or not. if yes, can you show me so i can inspect it if the above issue isn't your problem.

**Comment by yoooee** [comment]
I ran the following:
```
git clone https://github.com/Elecweb/emptytext.git emptytext
cd emptytext
npm install
npm run build
npm link
cd ..
ng new emptytext-use
cd emptytext-use
npm install
npm link emptytext
```
After running those commands, I updated the angular cli project emptytext-use as follows:
**app.module.ts**
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import { EmptyTextModule } from 'emptytext/dist';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    EmptyTextModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

**app.component.html**
`<empty-text></empty-text>`
Then in the angular cli app, I run the following:
`ng serve`
or
`ng server --preserve-symlinks`

This results in the following error:
ERROR in Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 194:50 in the original .ts file), resolving symbol NgModule.

I'm running:
node: v6.10.2
npm: 5.4.2
angular/cli: 1.4.3

**Comment by Elecweb** [comment]
@yoooee 
I'm not sure what is the issue. I'll try to find it.
Anyways, in the emptytext library, there's no component. It only have a directive. 

`<p emptytext></p>`

when you publish to npm or `link` you need to change current working directory to `dist` folder and `link` from there.
or you can create npm script

`"publish":"cd ./dist && npm link"`

and you need to import from just '"emptytext" 

`import { EmptyTextModule } from 'emptytext`

**Comment by yoooee** [comment]
@Elecweb

Thanks for the response.  I followed your directions and updated the arrow functions and everything seems to work now when I run ng serve --preserve-symlinks

Thanks again.
